apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-2
  description: A Java service scaffolded with Backstage
  tags:
    - springboot
    - java
    - maven
  annotations:
    # github.com/project-slug: dean-chin-altimetrik/test-2
    backstage.io/source-location: url:https://github.com/dean-chin-altimetrik/test-2/tree/
    backstage.io/techdocs-ref: url:https://github.com/dean-chin-altimetrik/test-2/tree/main/docs
    devbox.io/enabled: "true"
spec:
  type: service
  lifecycle: production
  owner: dean-chin-altimetrik
